bitlab_courses_store/articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment'),
]

bitlab_courses_store/bitlab_courses_store/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('shop/', include('shop.urls')),
    path('articles/', include('articles.urls')),
    path('grappelli/', include('grappelli.urls')),  # grappelli URLS
    path('admin/', admin.site.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bitlab_courses_store/shop/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

bitlab_courses_store/articles/models.py
import datetime
from django.db import models

from django.utils import timezone

class Article(models.Model):
    article_title = models.CharField('назваие статьи', max_length=255)
    article_text = models.TextField('текст статьи')
    pub_date = models.DateTimeField('дата публикации')

    def __str__(self):
        return self.article_title

    def was_published_recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days=7))

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField('имя автора', max_length=50)
    comment_text = models.CharField('текст комментария', max_length=255)

    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

bitlab_courses_store/shop/models.py
from django.db import models


class Category(models.Model):
    category_name = models.CharField('назваие категории', max_length=20, unique=True)

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    product_title = models.CharField('назваие продукта', max_length=20, unique=True)
    product_price = models.IntegerField(default=0)
    product_category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.product_title

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

bitlab_courses_store/articles/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render

from django.urls import reverse

from .models import Article

def index(request):
    latest_articles_list = Article.objects.order_by('-pub_date')[:5]
    return render(request, 'articles/list.html', {'latest_articles_list': latest_articles_list})

def detail(request, article_id):
    try:
        a = Article.objects.get( id = article_id)
    except:
        raise Http404("Статья не наидено!")

    latest_comments_list = a.comment_set.order_by('-id')[:10]

    return render(request, 'articles/detail.html', {'article': a, 'latest_comments_list': latest_comments_list})

def leave_comment(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Статья не наидено!")

    a.comment_set.create(author_name=request.POST['name'], comment_text=request.POST['text'])

    return HttpResponseRedirect( reverse('articles:detail', args=(a.id,)))

bitlab_courses_store/shop/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect

from django.urls import reverse

from .models import Category

def home(request):
    category = Category.objects.all()
    return render(request, 'index.html', context={'category': category})

def about(request):
    return render(request, 'about.html')

bitlab_courses_store/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}{{article.article_title}}{% endblock %}

{% block content %}

<h2>{{article.article_title}}</h2>

<p>{{article.article_text}}</p>

<em>{{article.pub_date}}</em>

{% if article.was_published_recently %}
НОВАЯ СТАТЬЯ!
{% endif %}

<hr>

{% if latest_comments_list %}

    {% for c in latest_comments_list %}
        <p>
            <strong>{{c.author_name}}</strong>
            <p>{{c.comment_text}}</p>
        </p>
    {% endfor %}

{% else %}
Коментарии не найдены! Можете стать первым ;)
{% endif %}

<hr>

<form action="{% url 'articles:leave_comment' article.id %}" method="POST">

    {% csrf_token %}

    <input type="text" required placeholder="Ваше имя" name="name"><br>
    <textarea name="text" required placeholder="Текст комментария" cols="30" rows="10"></textarea><br>

    <button type="submit">Оставить коментарий</button>

</form>

{% endblock %}

bitlab_courses_store/templates/articles/list.html
{% extends 'base.html' %}

{% block title %}Последние статьи{% endblock %}

{% block content %}

    {% if latest_articles_list %}

        {% for a in latest_articles_list %}
            <a href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a>
        {% endfor %}

    {% else %}
        Статьи не найдены )=
    {% endif %}

{% endblock %}

bitlab_courses_store/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Мой сайт{% endblock %}</title>
</head>
<body>

    {% block content %}{% endblock %}

</body>
</html>